#!/usr/bin/env python3
"""The values overlay `make e2e` layers last, built from the environment.

`make e2e` runs one ATS scenario against any cluster (Makefile.custom.mk,
tests/ats/README.md). A real cluster needs a real domain and a real identity
provider, and neither belongs in the repository, so the caller passes them in
the environment and this script turns them into a values file the target writes
to a temporary path and removes on exit.

None of the inputs is a credential: E2E_IDP_SECRET_NAME and E2E_IDP_CA_SECRET
are the NAMES of Secrets already on the cluster. The client secret itself lives
in the Secret the chart reads (global.identity.existingSecret) and, for the
tests' own logins, in ATS_CLIENT_SECRET in the caller's environment.

The overlay carries `global.identity` only when one of its keys is set: an
empty `identity:` is a null, which drops the whole block from every component
release. `make verify-scenarios` asserts that and the quoting.
"""

import json
import os
import sys
from typing import List

HEADER = "# Generated by make e2e from the environment. Not committed."

# The environment variable of each key, in the order the overlay renders them.
DOMAIN = "E2E_DOMAIN"
IDENTITY = (
    ("issuerUrl", "E2E_ISSUER_URL"),
    ("clientId", "E2E_CLIENT_ID"),
    ("existingSecret", "E2E_IDP_SECRET_NAME"),
)
CA_SECRET = "E2E_IDP_CA_SECRET"


def _scalar(value: str) -> str:
    """A value as a quoted YAML scalar. JSON's string form is valid YAML, so a
    value with a space, a `#`, a colon or a quote in it stays one scalar."""
    return json.dumps(value)


def overlay_lines(env: dict) -> List[str]:
    """The overlay's lines, empty when the environment names nothing."""
    domain = env.get(DOMAIN, "")
    identity = [(key, env.get(name, "")) for key, name in IDENTITY]
    ca_secret = env.get(CA_SECRET, "")
    if not domain and not any(value for _, value in identity) and not ca_secret:
        return []

    out = [HEADER, "global:"]
    if domain:
        out.append(f"  domain: {_scalar(domain)}")
    if any(value for _, value in identity) or ca_secret:
        out.append("  identity:")
        for key, value in identity:
            if value:
                out.append(f"    {key}: {_scalar(value)}")
        if ca_secret:
            out.append("    ca:")
            out.append(f"      secretName: {_scalar(ca_secret)}")
    return out


def main() -> int:
    lines = overlay_lines(dict(os.environ))
    if lines:
        print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
